name: Sync Fork

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两小时同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3  # 确保此处为最新或兼容Node.js 20的版本
    - name: Sync fork
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "blackmatrix7/ios_rule_script"
        source_branch: "main"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
